# -*- coding: utf-8 -*-
"""trophy and medals

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1keT0yfjgF6SwT3xSAtCqqBUfNIM0nXTB
"""

# Commented out IPython magic to ensure Python compatibility.
#clone YOLOv5 and
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="UC78tvvmXUYhxvbJH0E7")
project = rf.workspace("atharva-wlxfu").project("medals_trophy")
version = project.version(1)
dataset = version.download("yolov5")

!python train.py --img 640 --batch 16 --epochs 100 --data {dataset.location}/data.yaml --weights yolov5s.pt --cache

